### ISSUE TITLE
Request: mention pg-rxjs

### ISSUE THREAD

**Issue by jadbox** [coderhaoxin/pg-then#14]
I've created a library forked from this that's for Rx: 
[pg-rxjs](https://github.com/jadbox/pg-rxjs)

**Comment by jadbox** [comment]
Almost full code coverage is included too :)

**Comment by coderhaoxin** [comment]
:+1:

**Comment by coderhaoxin** [comment]
nice work!

**Comment by coderhaoxin** [comment]
d08c68ed50c2664b8b27d7b24bac2a774aef1519

**Comment by jadbox** [comment]
:+1: Thanks good sir! Btw, I'll see if I can maybe help you get a similar transaction method back into pg-then.

**Comment by coderhaoxin** [comment]
> 'll see if I can maybe help you get a similar transaction method back into pg-then

Welcome
