### ISSUE TITLE
another one :)

### ISSUE THREAD

**Issue by vitaly-t** [coderhaoxin/pg-then#5]
Kind of funny, we decided to publish this kind of thing almost at the same time :)

Mine is pg-promise: https://www.npmjs.com/package/pg-promise

I did the first publish only yesterday, and working hard on its documentation now. It is based on some good usage I got from it last year when I was trying to find an existing solution without luck, so I had to write one of my own.

**Comment by coderhaoxin** [comment]
glad to see. :tada:
