### ISSUE TITLE
It randomly gets stuck

### ISSUE THREAD

**Issue by nickretallack** [coderhaoxin/pg-then#6]
If I use this library for a while, it has a chance of getting stuck in a query and never returning.  Once this has happened, all future queries get stuck too.  This behavior is consistent with node-postgres' description of what happens when you leak connections from a pool.

Here is a program that demonstrates the problem.  It should be able to continue doing queries forever, but instead it gets stuck around try 18320 to 28906.

```javascript
var pg = require('pg-then');
var database_uri = 'postgresql://localhost:5432/test'
var pool = pg.Pool(database_uri)

var count = 0;
function test_forever() {
	count += 1;
	console.log("try", count)
	if (count > 100000) {
		console.log("success");
		return;
	pool.query('select 1 from pg_stat_activity').then(test_forever);
}

test_forever();
```

Here's the same thing the way node-postgres recommends you write it.  It continues forever:

```javascript
var pg = require('pg');
var database_uri = 'postgresql://localhost:5432/test'

var count = 0;
function test_forever() {
	count += 1;
	console.log("try", count)
	if (count >= 100000) {
		console.log("Success!")
		return;
	}

	pg.connect(database_uri, function(err, client, done) {
		var handleError = function(err) {
			if(!err) return false;
			if(client){
				done(client);
			}
			return true;
		};
		if(handleError(err)) return;

		client.query('select 1 from pg_stat_activity', function(err, result) {
			if(handleError(err)) return;
			done();
			test_forever();
		})
	})
}

test_forever();
```

**Comment by jonathanong** [comment]
no idea what's going on here...

**Comment by amxfonseca** [comment]
I'm also getting the same behavior. After 10 or so queries the system get's stuck. I jus't started to use this library yesterday, I didn't had the time to debug it yet. I will try to check it soon.

**Comment by coderhaoxin** [comment]
I'll take a look soon.

**Comment by coderhaoxin** [comment]
> it gets stuck around try 18320 to 28906

Because `Connection terminated`

**Comment by jonathanong** [comment]
@coderhaoxin i believe this is because we reuse the client. if we use `pg.connect()` on every query, we don't run into this problem.

**Comment by coderhaoxin** [comment]
Indeed, just take a glance at `pg`.

```js
PG.prototype.connect = function(config, callback) {
  ...
  var pool = this.pools.getOrCreate(config);
  pool.connect(callback);
  ...
};
```
